//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public ToDo()
        {
            this.ToDoEvents = new HashSet<ToDoEvent>();
        }
    
        public int ToDoId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ToDoEvent> ToDoEvents { get; set; }
    }
}
