//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoEvent
    {
        public int ToDoEventId { get; set; }
        public System.DateTime OccurredDttm { get; set; }
        public string Rating { get; set; }
        public string Comment { get; set; }
        public int ToDoId { get; set; }
    
        public virtual ToDo ToDo { get; set; }
    }
}
